apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-operator
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: k3s-fedora-do-a
        url: https://kubernetes.default.svc
      - cluster: k8s-managed-do
        url: https://dfbccd33-f11d-4103-b0d4-35c36f855e2c.k8s.ondigitalocean.com
  template:
    metadata:
      name: '{{cluster}}-istio-operator'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/istio/istio.git
        targetRevision: 1.12.1
        path: manifests/charts/istio-operator
      destination:
        server: '{{url}}'