apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: byeon-ca
  namespace: default
spec:
  secretName: byeon-ca-tls
  issuerRef:
    # The issuer created previously
    name: gcp-byeon-ca
  dnsNames:
  - "*.byeon.ca"
