apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gcp-byeon-ca
  namespace: istio-namespace1
spec:
  acme:
    email: alexandre@byeon.ca
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: gcp-byeon-ca-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: byeon-ca
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json