apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-manifests
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:kuuji/gitops.git
      revision: HEAD
      files:
      - path: "v2/clusters/**/.config.json"
  template:
    metadata:
      name: '{{cluster.name}}-cert-manager-manifests'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:kuuji/gitops.git
        targetRevision: HEAD
        path: v2/bases/system/cert-manager/manifests
        directory:
          recurse: true
      destination:
        server: '{{cluster.server}}'