apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: k3s-fedora-do-a
        url: https://kubernetes.default.svc
      - cluster: k8s-managed-do
        url: https://dfbccd33-f11d-4103-b0d4-35c36f855e2c.k8s.ondigitalocean.com
  template:
    metadata:
      name: '{{cluster}}-cert-manager'
    spec:
      project: "default"
      source:
        repoURL: git@github.com:kuuji/gitops.git
        targetRevision: HEAD
        path: v2/bases/system/cert-manager
      directory:
        recurse: true
      destination:
        server: '{{url}}'