apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-ui
  namespace: istio-namespace1
spec:
  hosts:
  - argocd.byeon.ca
  gateways:
  - istio-namespace1/pub-lb
  http:
  - name: "argocd"
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local