apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationset-controller
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/argoproj-labs/applicationset.git
    targetRevision: v0.3.0
    path: manifests/base

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd