apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bitnami-sealed-secrets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: k3s-fedora-do-a
        url: https://kubernetes.default.svc
      - cluster: k8s-managed-do
        url: https://dfbccd33-f11d-4103-b0d4-35c36f855e2c.k8s.ondigitalocean.com
  template:
    metadata:
      name: '{{cluster}}-bitnami-sealed-secrets'
    spec:
      project: "default"
      destination:
        server: '{{url}}'
        namespace: kube-system
      source:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.0.0
        chart: sealed-secrets
        helm:
          releaseName: sealed-secrets