apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bitnami-sealed-secrets
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:kuuji/gitops.git
      revision: HEAD
      files:
      - path: "v2/clusters/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-bitnami-sealed-secrets'
    spec:
      project: "default"
      destination:
        server: '{{cluster.server}}'
        namespace: kube-system
      source:
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        targetRevision: 2.0.0
        chart: sealed-secrets
        helm:
          releaseName: sealed-secrets