apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: gh-registry-secret
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgB+TM4vgOX6m9xJKHyg4B2MSAOrWvyWMEzE5NgbKNoMsKPgj2Yyb2mcWJzhU6IW8RykLcY7SfZiQX9210/NkCP/GMSYB2+6nZIEPhh+mEVGIVXBOmqVEsJP/vDCOD7s44W0dlMPLteI/pDFirOcmEosD+11Csr5KcEUGa2ee/hGPh8C25on116YTt4jK07SwJM5gSbcF2d3yLyVtgH4sw74qvX4gESDQs7aW3ynSdmwhrLA7ZsqLvz2du6AxiR86NKdCeOK7RoHWP2oS0MMk1ObUudPxCYgQWKLguX4e1BMvC5VjFViYtc1Q80ghoVSkTxph59ngvHmKLkwVxdIhjqovLHORxssD/YK6wCsWuWNKUSkdddTRMDdgjr1XLoLekJHmtIHThbE4Nz8XPGMNzbPV9kJruV+7UVxclkT01UXx/bPSIbOm1FYmtHkBRoql409ZEL5LotSSOM8Ju3X1g7zAizwD8lnw3AISX/A+cxXH5AkIp2iUtFw1ilPNCyL2KGkrwDoH/HXY4bgH9D2IK99rQ/rvpbx0XUIW1lRpCHSyr0H36zV0aqb7lbMCqIlCXLe9IJJUKtIGnCAXTP63xeIfHJXhXDB6wB+izhIZV8O4n91+Q2B+PfvtP4N1T8AfFd2iVAec1Od+k7G5Kkdee5OXWkk0pYmqfHw41/HeTCrLG6fGojZB0yJWRbLqk/bUzd5fqm2mAQDbb8R2F6RvInFIYnODmpsjIL5bsi7IZfHkq3bGblx1f/CRYK+8Onnptr8cif/I+9xMqXXxWrebXCq5GuZRFiTbvbCHbhAmqs9nPVQGFcXSEqjEI5anjh7qHdWrW/PAho8HJs6e7ZL1QbBu+yW
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: gh-registry-secret
      namespace: argocd
    type: kubernetes.io/dockerconfigjson

