---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuuji
  namespace: argocd
spec:
  source:
    path: clusters/k8s-managed-do/kuuji
  destination:
    server: https://dfbccd33-f11d-4103-b0d4-35c36f855e2c.k8s.ondigitalocean.com
