apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-fedora-do-root
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/k3s-fedora-do
    repoURL: git@github.com:kuuji/gitops.git
    targetRevision: HEAD