apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-sealed-secrets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  destination:
    server: https://dfbccd33-f11d-4103-b0d4-35c36f855e2c.k8s.ondigitalocean.com