apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-sealed-secrets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  destination:
    server: do-nyc1-k8s-1-21-5-do-0-nyc1-1640271152489