---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gofun-2
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:kuuji/gitops.git
      revision: HEAD
      files:
      - path: "v2/clusters/**/.gofun.yaml"
  template:
    metadata:
      name: 'go-fun-2'
      annotations:
        argocd-image-updater.argoproj.io/image-list: gofun=ghcr.io/kuuji/project/app
        argocd-image-updater.argoproj.io/gofun.allow-tags: regexp:^pre-production-.*$
        argocd-image-updater.argoproj.io/gofun.helm.image-spec: gofun.containers[0].image
        argocd-image-updater.argoproj.io/gofun.pull-secret: pullsecret:argocd/gh-registry-secret
        argocd-image-updater.argoproj.io/gofun.update-strategy: latest
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      # The project the application belongs to.
      project: default

      source:
        repoURL: https://charts.devspace.sh
        targetRevision: 0.8.4
        chart: component-chart
        # helm specific config
        helm:

          # Release name override (defaults to application name)
          releaseName: gofun

          # Values file as block file
          values: |
            '{{values}}'
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: kuuji
