---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gofun
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:kuuji/gitops.git
      revision: HEAD
      files:
      - path: "v2/clusters/**/.config.json"
  template:
    metadata:
      name: '{{cluster.name}}-go-fun'
      annotations:
        argocd-image-updater.argoproj.io/image-list: gofun=ghcr.io/kuuji/project/app
        argocd-image-updater.argoproj.io/gofun.allow-tags: regexp:^pre-production-.*$
        argocd-image-updater.argoproj.io/gofun.helm.image-spec: containers[0].image
        argocd-image-updater.argoproj.io/gofun.pull-secret: pullsecret:argocd/gh-registry-secret
        argocd-image-updater.argoproj.io/gofun.update-strategy: latest
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: git@github.com:kuuji/gitops.git
        targetRevision: HEAD
        path: v2/clusters/{{cluster.name}}/kuuji/go_fun
        # helm specific config
        helm:
          releaseName: gofun
      # Destination cluster and namespace to deploy the application
      destination:
        server: '{{cluster.server}}'
        namespace: kuuji

      # Sync policy
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        #   prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
        #   selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        #   allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.

