apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kuuji
  namespace: argocd
spec:
  # Project description
  description: Kuuji tenant

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: kuuji
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'networking.istio.io'
    kind: VirtualService
  - group: 'networking.istio.io'
    kind: DestinationRule
  - group: 'argoproj.io'
    kind: Application
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: ''
    kind: Service

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to kuuji
    policies:
    - p, proj:kuuji:read-only, applications, get, kuuji/*, allow
